<?php

return [
    [
        'title' => 'test title 1',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => 199,
        'new' => true,
        'img'  => '/img/Layer%20311.png',
    ],
    [
        'title' => 'test title 2',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/Layer%20312.png',
    ],
    [
        'title' => 'test title 3',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 125,
        'new' => true,
        'discountCost' => null,
        'img'  => '/img/Layer%20313.png',
    ],
    [
        'title' => 'test title 4',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 111,
        'discountCost' => 90,
        'new' => false,
        'img'  => '/img/Layer%20314.png',
    ],
    [
        'title' => 'test title 5',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => 100,
        'new' => true,
        'img'  => '/img/Layer%20315.png',
    ],
    [
        'title' => 'test title 6',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/Layer%20316.png',
    ],
    [
        'title' => 'test title 7',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/Layer%20317.png',
    ],
    [
        'title' => 'test title 8',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/Layer%20318.png',
    ],
    [
        'title' => 'test title 9',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/img_product.png',
    ],
];
